FROM golang:1.24.2-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o offertrack ./cmd/offertrack

FROM alpine:3.21 AS runner
RUN apk add --no-cache pandoc ca-certificates
WORKDIR /app
COPY --from=builder /app/offertrack .
COPY config/ ./config/
ENTRYPOINT ["./offertrack"]
